# Generated by Django 6.0 on 2026-01-21 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foot_width', models.CharField(choices=[('Narrow', 'Narrow'), ('Regular', 'Regular'), ('Wide', 'Wide')], default='Regular', max_length=20)),
                ('arch_type', models.CharField(choices=[('Flat', 'Flat Foot (Low Arch)'), ('Normal', 'Normal Foot (Medium Arch)'), ('High', 'Hollow Foot (High Arch)')], default='Normal', max_length=20)),
                ('uses_orthotics', models.BooleanField(default=False, help_text='Do you use custom orthotics?')),
                ('injury_history', models.JSONField(blank=True, default=list, help_text='List of past injuries')),
                ('weight_kg', models.IntegerField(default=50, help_text='Weight in KG')),
                ('preferred_terrain', models.CharField(choices=[('Road', 'Road / Treadmill / Track (Aspal/Lintasan)'), ('Trail', 'Trail (Tanah/Gunung/Off-road)')], default='Road', max_length=20)),
                ('running_purpose', models.CharField(choices=[('Daily', 'Daily Training (Lari Santai/Jogging)'), ('Speed', 'Speed/Tempo (Lari Cepat/Interval)'), ('Race', 'Racing (Lomba/Marathon)'), ('Recovery', 'Recovery (Jalan/Lari Ringan)')], default='Daily', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
