# Generated by Django 6.0 on 2026-01-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_terrain',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='running_purpose',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='arch_type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Normal', 'Normal'), ('High', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foot_width',
            field=models.CharField(choices=[('Narrow', 'Narrow'), ('Regular', 'Regular'), ('Wide', 'Wide')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='injury_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uses_orthotics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_kg',
            field=models.IntegerField(),
        ),
    ]
